config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'session#new'

  get '/weather_search' => 'pages#weather_search'
  get '/location_search' => 'pages#location_search'
  post '/location_search' => 'pages#location_search_result'

  get '/player' => 'pages#player'
  
  resources :users
  resources :history
  resources :tracks_history

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

#               Prefix Verb   URI Pattern                        Controller#Action
#                 root GET    /                                  pages#home
#       weather_search GET    /weather_search(.:format)          pages#weather_search
#      location_search GET    /location_search(.:format)         pages#location_search
#                      POST   /location_search(.:format)         pages#location_search_result
#               player GET    /player(.:format)                  pages#player
#                users GET    /users(.:format)                   users#index
#                      POST   /users(.:format)                   users#create
#             new_user GET    /users/new(.:format)               users#new
#            edit_user GET    /users/:id/edit(.:format)          users#edit
#                 user GET    /users/:id(.:format)               users#show
#                      PATCH  /users/:id(.:format)               users#update
#                      PUT    /users/:id(.:format)               users#update
#                      DELETE /users/:id(.:format)               users#destroy
#        history_index GET    /history(.:format)                 history#index
#                      POST   /history(.:format)                 history#create
#          new_history GET    /history/new(.:format)             history#new
#         edit_history GET    /history/:id/edit(.:format)        history#edit
#              history GET    /history/:id(.:format)             history#show
#                      PATCH  /history/:id(.:format)             history#update
#                      PUT    /history/:id(.:format)             history#update
#                      DELETE /history/:id(.:format)             history#destroy
# tracks_history_index GET    /tracks_history(.:format)          tracks_history#index
#                      POST   /tracks_history(.:format)          tracks_history#create
#   new_tracks_history GET    /tracks_history/new(.:format)      tracks_history#new
#  edit_tracks_history GET    /tracks_history/:id/edit(.:format) tracks_history#edit
#       tracks_history GET    /tracks_history/:id(.:format)      tracks_history#show
#                      PATCH  /tracks_history/:id(.:format)      tracks_history#update
#                      PUT    /tracks_history/:id(.:format)      tracks_history#update
#                      DELETE /tracks_history/:id(.:format)      tracks_history#destroy
#                login GET    /login(.:format)                   session#new
#                      POST   /login(.:format)                   session#create
#                      DELETE /login(.:format)                   session#destroy

app/views/layouts/application.html.erb
<!--
  __      __  ____    ______      ____                                  __        ____                
/\ \  __/\ \/\  _`\ /\__  _\    /\  _`\              __               /\ \__    /\  _`\              
\ \ \/\ \ \ \ \ \/\ \/_/\ \/    \ \ \L\ \_ __   ___ /\_\     __    ___\ \ ,_\   \ \ \L\ \  __  __    
 \ \ \ \ \ \ \ \ \ \ \ \ \ \     \ \ ,__/\`'__\/ __`\/\ \  /'__`\ /'___\ \ \/    \ \  _ <'/\ \/\ \   
  \ \ \_/ \_\ \ \ \_\ \ \_\ \__   \ \ \/\ \ \//\ \L\ \ \ \/\  __//\ \__/\ \ \_    \ \ \L\ \ \ \_\ \  
   \ `\___x___/\ \____/ /\_____\   \ \_\ \ \_\\ \____/\ \ \ \____\ \____\\ \__\    \ \____/\/`____ \ 
    '\/__//__/  \/___/  \/_____/    \/_/  \/_/ \/___/\ \_\ \/____/\/____/ \/__/     \/___/  `/___/> \
                                                    \ \____/                                   /\___/
        ____    ______  __      __              ____ \/_____    ______  ____    __      ____   \/__/ 
   __  /\  _`\ /\__  _\/\ \    /\ \            /\  _`\ /\  _`\ /\  _  \/\  _`\ /\ \    /\  _`\       
  /'_`\\ \ \L\ \/_/\ \/\ \ \   \ \ \           \ \,\L\_\ \ \L\_\ \ \L\ \ \ \L\ \ \ \   \ \ \L\_\     
 /'/'_` \ \  _ <' \ \ \ \ \ \  _\ \ \  __       \/_\__ \\ \  _\L\ \  __ \ \ ,  /\ \ \  _\ \  _\L     
/\ \ \L\ \ \ \L\ \ \_\ \_\ \ \L\ \ \ \L\ \        /\ \L\ \ \ \L\ \ \ \/\ \ \ \\ \\ \ \L\ \ \ \L\ \   
\ \ `\__,_\ \____/ /\_____\ \____/\ \____/        \ `\____\ \____/\ \_\ \_\ \_\ \_\ \____/\ \____/   
 \ `\_____\\/___/  \/_____/\/___/  \/___/   _______\/_____/\/___/  \/_/\/_/\/_/\/ /\/___/  \/___/    
  `\/_____/                                /\______\                                                 
                                           \/______/    
@bill_searle
-->
<!DOCTYPE html>
<html>
<head>
  <title>WeatherifyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<div class="container">

		<div class="text-center jumbotron">
		<h1 class="title">
			<%= link_to("Weatherify", @current_user.present? ? location_search_path : login_path) %>
		</h1>
		</div>

			<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class = "container-fluid">
			  		<ul class="nav navbar-nav">
			  			<%== smartnav %>
			  		</ul>
			  	</div>
			</nav>

			<%= yield %>
			
		</div>
		<footer>
			<p><small class="text-center">a #WDI5 project by @bill_searle.<small></p>
		</footer>	
	</body>
</html>